.\" (c) Rasca, Berlin 1997-98 & Karl H. Beckers 2003-06
.\" Published under the GNU GPL V2
.TH XVIDCAP 1 "September 2006" "GNU" "Version 1.1.4"
.SH NAME
xvidcap \- video capturing program for X windows
.SH SYNOPSIS
.B xvidcap
'R [
'B -v
'R ]\ [
'B --mf
'R |
'B --sf
'R ]\ [
'B --fps
'I fps
'R ]\ [
'B --time
'I seconds
'R ]\ [
'B --frames
'I frames
'R ]\ [
'B --continue
'R [yes|no]]\ [
'B --cap_geometry
'I wxh+x+y
'R ]\ [
'B --start_no
'I start_number
'R ]\ [
'B --rescale
'I percent 
'R ]\ [
'B --quality
'I quality
'R ]\ [
'B --source
'R x11|shm|v4l]\ [
'B --file
'I file
'R ]\ [
'B --gui
'R [yes|no]]\ [
'B --auto
'R ]\ [
'B --codec
'I codec
'R ]\ [
'B --codec-help
'R ]\ [
'B --format
'I format
'R ]\ [
'B --format-help
'R ]\ [
'B --aucodec
'I audio codec
'R ]\ [
'B --aucodec-help
'R ]\ [
'B --audio
'R [yes|no]]\ [
'B --audio_in
'I device
'R |-]\ [
'B --audio_bits
'I bit_rate
'R ]\ [
'B --audio_rate
'I sample_rate
'R ]\ [
'B --audio_channels
'I channels
'R ]

.SH INTRODUCTION

.B xvidcap
is a tool that captures movement on a selected area of an X11
screen to files. It can operate in two distinct modes: (1)
'B single-frame
capture or (2) 
'B multi-frame
capture. In single-frame capture mode xvidcap makes a
configurable number of screenshots per second and saves them to individual
files. In multi-frame capture mode xvidcap also takes a number of screenshots
per second, but encodes them to a single video in real time. Audio capture 
is only available with multi-frame formats.

Recording in single-frame capture mode may be more convenient if you wish
to preprocess the images before encoding, or if you need other video 
codecs xvidcap does not support. Individual images can later be encoded 
with tools like ffmpeg, mencoder, or transcode.

For help, feature requests, or bug-reports please turn to
http://www.sourceforge.net/projects/xvidcap/ .

.SH OPTIONS

.IP  "\f[B]-v
Runs xvidcap in verbose mode. This will provide more information about
user settings, input and output codecs, performance and so forth. Messages
like "missing XX milli secs .." while capturing mean you are missing 
frames due to lack of ressources (dropped frames). This results in a video 
that will play back too quickly. Note though, that verbose mode slows down 
xvidcap and may actually be causing frame drops. Try running without 
verbose mode and watch the frame drop monitor.

.IP  "\f[B]--mf\f[R]\ |\ \f[B]--sf
Xvidcap tries to be smart about what capture mode you want. If you 
specify "--file test.avi" xvidcap will assume you want multi-frame capture.
You can explicitly specify capture mode on the command line with this
switch. If, for example, you have your settings properly configured and
saved with multi-frame capture as the default mode, calling "xvidcap --sf" will
start xvidcap in single-frame capture mode with all stored settings. The
default is multi-frame capture.

.IP "\f[B]--fps\ \f[I]fps
Specifies the number of frames to be captured per second. This parameter 
accepts floating point values, which allows for very low capture rates like
e.g. "--fps 0.5" to record one frame every 2 seconds. This is only possible
in single-frame mode. Codecs used for multi-frame modes usually only
accept certain frame rates as valid. Note that fractional frame rates for 
codecs like MPEG1 which only accept very specific fractions are disabled 
in this version due to an inconsistency with fractional timing between 
xvidcap and libavcodec. Only integer frames rates will be accepted here.

.IP "\f[B]--time \f[I]seconds
Specifies the maximum time to capture, if "0" xvidcap will capture until 
stopped interactively. For any other value any recording session will
stop automatically after the specified number of seconds. This parameter 
conflicts with "--frames" (see below). If both are given xvidcap stop capturing
if either applies. The program accepts floating point values, e.g. "2.5".

.IP "\f[B]--frames\ \f[I]number of frames
Stops capturing after the specified number of frames are captured. If "0"
xvidcap will capture until stopped interactively, ref. "--time" above.

.IP "\f[B]--continue\ \f[R][yes|no]
When multi-frame capture is selected, maximum recording time or frames are
specified, and the output filename is incrementable (see "--file" below),
xvidcap can automatically continue to capture to a new file when one 
exceeds the maximum recording time or number of frames. This will change
the behaviour of "--time" and "--frames" because recording will not stop
at the specified limits, but rather start a new video file. The feature is 
esp. useful if you want to automatically split your recording into chunks of
e. g. five minutes. If no argument to "--continue" is given, xvidcap defaults to "no".
Because single-frame capture needs an incrementable filename to count the
individual frames, this feature is disabled for single-frame capture. 

.IP "\f[B]--cap_geometry\ \f[I]WIDTH\f[R]x\f[I]HEIGHT\f[R]+\f[I]XPOSITION\f[R]+\f[I]YPOSITION
Override the default width and height of the capture frame. Use the picker
button of the GUI rather than this command line option to adjust the frame size to a 
given window. Capture sizes below 20 x 20 don't seem to work well with 
most multi-frame capture codecs.

.IP "\f[B]--start_no\ \f[I]start_number
Defines the start number which should be used for numbering files. The default 
value is "0".This parameter is used for single-frame capture only.
The numbering of movie files for "--continue" always starts at zero.

.IP "\f[B]--rescale\ \f[I]relative output size
Rescale the output to a percentage of the original input. A value of "25", e. g.
makes the output size be 20 percent of the original input area.

.IP "\f[B]--quality\ \f[I]quality
Specify a value between "0" and "100" to define the quality encoding. The 
default value is "75". 

.IP "\f[B]--source\ \f[R]x11|shm
Enable or disable the usage of the X11 shared memory extension. For shared 
memory support both client and server have to run on the same host. If shared
memory support is available, xvidcap will use it by default. If your X server and
client do not run on the same machine, you need to disable it by passing "--source x11".

.IP "\f[B]--file\ \f[I]file
File name or pattern to use for saving the captured frames. A file name
pattern contains printf()-like formatting (ref. 
'B man printf
) information to make the file
name incrementable, e.g. "--file "out-%02d.xwd"". This is necessary for 
single-frame capture. xvidcap will replace the first printf()
format string with the number of the frame currently captured. Thus, in
the example given, it will write to files out-00.xwd, out-01.xwd, out-02.xwd,
etc. The frame number to start with can be specified with "--start_no",
see above.
.br
Multi-frame capture does not need a file pattern. If you specify one
nonetheless like "--file "mymovie-%d.mpeg"", xvidcap will replace the format
string with the number of the current recording session (always starting
the count from zero). This will enable you to manually in-/decrement that
number, or use the autocontinue feature (ref. "--continue" above) effectively
creating a series of video files.

.IP "\f[B]--gui\ \f[R][yes|no]
Start xvidcap with or without control GUI overriding what's in the
preferences file. Running without GUI will automatically start a single
capture session. It can be stopped by either specifying one of "--time" or
"--frames", or by hitting CTRL-C.

.IP "\f[B]--codec\ \f[I]codec
Override preferences and automatic codec selection with the explicitly
specified codec.

.IP "\f[B]--codec-help
List valid codecs.

.IP "\f[B]--format\ \f[I]format
Override preferences and automatic format selection with the explicitly
specified file format.

.IP "\f[B]--format-help
List valid file formats.

.SH AUDIO SUPPORT

On systems where FFMPEG supports audio capture, you will be able to add
an audio stream to a recording session while in multi-frame capture mode.
Audio streams can either be captured from a compatible audio device (e.g. 
"/dev/dsp") or from stdin (cf. "--audio_in" below). 

.IP "\f[B]--audio\ \f[R][yes|no]
Enable or disable audio capture using default parameters or those saved to the
preferences file. If supported this is enabled by default for multi-frame capture.

.IP "\f[B]--audio_in\ \f[I]device\f[R]|-
Capture audio from the specified device or from stdin. The latter allows
for dubbing a captured video using a command line like the following. The 
default is "/dev/dsp".

cat some.mp3 | xvidcap --audio_in -

.IP "\f[B]--audio_rate\ \f[I]sample rate
Set the desired sample rate. The default is "22050" Hz. Note that when using
stdin input the input file will be resampled as needed.

.IP "\f[B]--audio_bits\ \f[I]bit rate
Set the desired bit rate. The default is "32000" bit. Note that when using
stdin input the input file will be resampled as needed.

.IP "\f[B]--audio_channels\ \f[I]number of channels
Set the desired number of channels. The default is "1" for mono. Any value
above "2" is probably only useful with stdin input and a 5-channel AC audio
input file.

.IP "\f[B]--aucodec\ \f[I]audio codec
Override preferences and automatic codec selection with the explicitly
specified audio codec.

.IP "\f[B]--aucodec-help
List valid audio codecs.

.SH AUTHORS
Rasca Gmelch, Karl H. Beckers
.br
http://www.sourceforge.net/projects/xvidcap/
.br
XVidCap is published under the GNU General Public License.

