'\" -*- coding: iso8859-1 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH xvidcap-dbus-client 1 "23 May 2008" "Mai 2008" ""
.SH NAME
XVidCap D-BUS Client \- Fernsteuerung f\(:ur XVidCap
.SH SYNOPSIS
'nh
.fi
.ad l
\fBxvidcap-dbus-client\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[--action start|stop|pause ]
'in \n(.iu-\nxu
.ad b
'hy
.SH BESCHREIBUNG
xvidcap-dbus-client ist ein Werkzeug zum Steuern einer xvidcap Aufnahme von au\(sserhalb xvidcap selbst. Der wesentliche Verwendungszweck ist die Steuerung von der Kommandozeile aus oder im Zusammenhang mit Tastatur-K\(:urzeln.
.PP
For inter process communication this utility uses D-BUS. If xvidcap is not running when this
program is invoked to trigger an action, xvidcap is started through D-BUS activation. 
For help, feature requests, or bug-reports please turn to http://www.sourceforge.net/projects/xvidcap/
.SH OPTIONEN
Dieses Program folgt der g\(:angigen GNU Befehlszeilen-Syntax bei der lange Optionen mit zwei Bindestrichen (\*(T<\-\-\*(T>) beginnen. Folgende Optionen sind m\(:oglich:
.TP 
\*(T<\fB\-\-action \fR\*(T>start|stop|pause
Hiermit wird der Befehl an xvidcap gesendet, eine Aufnahme entweder zu starten oder zu stoppen, oder eine Pause einzulegen, bzw. diese zu beenden. Falls xvidcap nicht l\(:auft, wird es gestartet.
.SH AUTOREN
xvidcap-dbus-client wurde entwickelt von Karl H. Beckers.
.PP
Diese manpage wurde von Karl H. Beckers <\*(T<karl.h.beckers@gmx.net\*(T>> f\(:ur das xvidcap Project geschrieben.
.PP
Karl H. Beckers 
.PP
Die Genehmigung dieses Dokument zu kopieren, verteilen und/oder zu ver\(:andern wird erteilt im Rahmen der GNU Free Documentation License Version 1.1 oder jeglicher sp\(:aterer Version, die durch die Free Software Foundation herausgegeben wurde; ohne unver\(:anderliche Abschnitte, Voder- oder R\(:uckseiten Texte.
